apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-min-pv-local
  namespace: default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "mysql-min-storageclass-nfs"
  persistentVolumeReclaimPolicy: Retain
  #存储采用nfs
  nfs:
    path: /mysql-min
    server: xxx.nas.aliyuncs.com
