filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.dashboards.enabled: false

setup.kibana:
  host: "http://kafka:5601"
output.kafka:
  hosts: ["kafka:9092"]
  topic: 'logs'
  codec.json:
    pretty: false