apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.2
imageRepository: registry.aliyuncs.com/k8sxio
apiServer:
  certSANs:    #填写所有kube-apiserver节点的hostname、IP、VIP
  - k8s-master-1
  - k8s-master-2
  - k8s-master-3
  - k8s-worker-1
  - k8s-worker-2
  - k8s-worker-3
  - apiserver.demo
  - 172.16.106.208
  - 172.16.106.80
  - 172.16.106.14
  - 127.16.106.130
  - 172.16.106.149
  - 172.16.106.195
  - 172.16.106.187
controlPlaneEndpoint: "apiserver.demo:6443"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.100.0.1/16"
  dnsDomain: "cluster.local"
